name: gpt_clone_flutter
description: "A new Flutter project for a GPT-like clone."
publish_to: 'none' # Este proyecto no se publicará en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.2           # Manejo de solicitudes HTTP al backend
  provider: ^6.0.5      # Gestión de estado
  flutter_bootstrap: ^1.0.0  # Diseño adaptativo responsivo (opcional)
  cupertino_icons: ^1.0.8  # Iconos estilo iOS
  shelf: ^1.5.0        # Framework ligero para servidores HTTP
  shelf_router: ^1.0.0 # Para definir rutas
  shelf_static: ^1.0.0 # Para servir archivos estáticos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Reglas de lint recomendadas para buenas prácticas

flutter:
  uses-material-design: true

