name: gpt_clone_flutter
description: "A new Flutter project for a GPT-like clone."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.2           # Manejo de solicitudes HTTP al backend
  provider: ^6.1.2      # Gesti칩n de estado
  flutter_bootstrap: ^2.0.0  # Dise침o adaptativo responsivo (opcional)
  cupertino_icons: ^1.0.8  # Iconos estilo iOS
  shelf: ^1.4.0         # Framework ligero para servidores HTTP (compatible con SDK 3.5.4)
  shelf_router: ^1.0.0  # Para definir rutas
  shelf_static: ^1.0.0  # Para servir archivos est치ticos
  process_run: ^1.2.2+1  # Para ejecutar comandos del sistema
  flutter_dotenv: ^5.0.2
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Reglas de lint recomendadas para buenas pr치cticas

flutter:
  uses-material-design: true
  assets:
    - assets/.env

